<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Error S2801: [Virtuoso Driver]CL033: Connect failed to localhost:13001 = localhost:13001.at line 0.. - 编程大白的博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="Error S2801: [Virtuoso Driver]CL033: Connect failed to localhost:13001 = localhost:13001.at line 0.." />
<meta property="og:description" content="一般情况下，启动virtuoso使用命令&#34; virtuoso-t -fd&#34; ，但是我这里是通过运行 py文件 开启服务，所以跟之前的方法还是不太一样的。
具体的参考源码链接如下：
GitHub - dki-lab/Freebase-Setup: The last data dump of Freebase with introductory explanation of its schema
开启服务
$ python3 virtuoso.py start 3001 -d virtuoso_db
运行之后出错：
关闭服务
$ python3 virtuoso.py stop 3001 运行之后出错：
经过我反复排查，最终发现是因为我之前在已经开启服务的情况下再次开启服务导致的错误。
我用命令查有关virtuoso的进程：
$ ps -ef | grep virtuoso
然后将不相关的进程用kill 杀死：
$ kill -9 7428
这时测试一下 重启服务，关闭服务，发现问题已经解决了！！
最后，网上有关virtuoso 启动失败的资料很少，所以查找起来原因有些困难，希望大家遇到新奇的bug都能记录下来，我们互帮互助，早点解决bug！！" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://bcdabai.github.io/posts/c2566c15c5c26047fa6c8aec241a1993/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2022-09-02T01:02:22+08:00" />
<meta property="article:modified_time" content="2022-09-02T01:02:22+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大白的博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大白的博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">Error S2801: [Virtuoso Driver]CL033: Connect failed to localhost:13001 = localhost:13001.at line 0..</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p>一般情况下，启动virtuoso使用命令" virtuoso-t  -fd" ，但是我这里是通过运行 py文件 开启服务，所以跟之前的方法还是不太一样的。</p> 
<p></p> 
<p>具体的参考源码链接如下：</p> 
<p><a href="https://github.com/dki-lab/Freebase-Setup" title="GitHub - dki-lab/Freebase-Setup: The last data dump of Freebase with introductory explanation of its schema">GitHub - dki-lab/Freebase-Setup: The last data dump of Freebase with introductory explanation of its schema</a></p> 
<p></p> 
<p><strong>开启服务</strong></p> 
<blockquote> 
 <p>$ python3 virtuoso.py start 3001 -d virtuoso_db</p> 
</blockquote> 
<p>运行之后出错：</p> 
<p><img alt="" height="548" src="https://images2.imgbox.com/ba/8e/jas0GIuQ_o.png" width="1200"></p> 
<p> </p> 
<p><strong>关闭服务</strong></p> 
<blockquote> 
 <p>$ python3 virtuoso.py stop 3001 </p> 
</blockquote> 
<p>运行之后出错：</p> 
<p><img alt="" height="128" src="https://images2.imgbox.com/8b/f6/2Q0OXbbu_o.png" width="1160"> </p> 
<p></p> 
<p> 经过我反复排查，最终发现是因为我之前在已经开启服务的情况下再次开启服务导致的错误。</p> 
<p>我用命令查有关virtuoso的进程：</p> 
<blockquote> 
 <p>$ ps  -ef  | grep  virtuoso</p> 
</blockquote> 
<p><img alt="" height="85" src="https://images2.imgbox.com/34/ff/0dN9fTN0_o.png" width="1200"></p> 
<p>然后将不相关的进程用kill 杀死：</p> 
<blockquote> 
 <p>$ kill -9  7428</p> 
</blockquote> 
<p><img alt="" height="85" src="https://images2.imgbox.com/4c/dc/3h8I2tdg_o.png" width="1200"></p> 
<p>这时测试一下  重启服务，关闭服务，发现问题已经解决了！！</p> 
<p><img alt="" height="85" src="https://images2.imgbox.com/13/94/pFaBqJI9_o.png" width="1179"> </p> 
<p> 最后，网上有关virtuoso 启动失败的资料很少，所以查找起来原因有些困难，希望大家遇到新奇的bug都能记录下来，我们互帮互助，早点解决bug！！</p> 
<p></p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/3187f744955dd77c90cf61f181c67ab2/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">数组模拟邻接表（链式前向星）</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/d23c6b91e49d7d1da15ed641dab8c07d/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">猿创征文｜＜JDBC＞多种开源数据库连接池</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大白的博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>