<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Java基础知识之异常Exception - 编程大白的博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="Java基础知识之异常Exception" />
<meta property="og:description" content="1、什么是异常，java提供异常处理机制有什么用？
以下程序执行过程中发生了不正常的情况，而这种不正常的情况叫做：异常
java语言是很完善的语言，提供了异常的处理方式，以下程序执行过程中出现了不正常情况，
java把该异常信息打印输出到控制台，供程序员参考。程序员看到异常信息之后，可以对
程序进行修改，让程序更加的健壮。
什么是异常：程序执行过程中的不正常情况。
异常的作用：增强程序的健壮性。
2、以下程序执行控制台出现了：
Exception in thread &#34;main&#34; java.lang.ArithmeticException: / by zero
at com.bjpowernode.javase.exception.ExceptionTest01.main(ExceptionTest01.java:14)
这个信息被我们称为：异常信息。这个信息是JVM打印的。
3. 异常在java中以类的形式存在，每一个异常类都可以创建异常对象。
4.处理异常的第一种方式：
在方法声明的位置上使用throws关键字抛出，谁调用我这个方法，我就抛给谁。抛给调用者来处理。
这种处理异常的态度：上报。
处理异常的第二种方式：
使用try..catch语句对异常进行捕捉。
这个异常不会上报，自己把这个事儿处理了。
异常抛到此处为止，不再上抛了。
注意：
只要异常没有捕捉，采用上报的方式，此方法的后续代码不会执行。
另外需要注意，try语句块中的某一行出现异常，该行后面的代码不会执行。
try..catch捕捉异常之后，后续代码可以执行。
在以后的开发中，处理编译时异常，应该上报还是捕捉呢，怎么选？
如果希望调用者来处理，选择throws上报。
其它情况使用捕捉的方式。
5.深入try..catch
1、catch后面的小括号中的类型可以是具体的异常类型，也可以是该异常类型的父类型。
2、catch可以写多个。建议catch的时候，精确的一个一个处理。这样有利于程序的调试。
3、catch写多个的时候，从上到下，必须遵守从小到大。
6.异常对象的两个方法：
String msg = e.getMessage();
e.printStackTrace(); // 一般都是使用这个。
我们以后查看异常的追踪信息，我们应该怎么看，可以快速的调试程序呢？
异常信息追踪信息，从上往下一行一行看。
但是需要注意的是：SUN写的代码就不用看了(看包名就知道是自己的还是SUN的。)。
主要的问题是出现在自己编写的代码上。
例如：
/*
java.io.FileNotFoundException: C:\jetns-agent.jar (系统找不到指定的文件。)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:155)
at java.base/java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:110) //sun的代码
at com.bjpowernode.javase.exception.ExceptionTest09.m3(ExceptionTest09.java:31) //自己代码出现的异常" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://bcdabai.github.io/posts/897bb2fb5c9bb1193c2b49bfda9a9bce/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2021-03-22T15:01:20+08:00" />
<meta property="article:modified_time" content="2021-03-22T15:01:20+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大白的博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大白的博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">Java基础知识之异常Exception</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p>1、什么是异常，java提供异常处理机制有什么用？<br>     以下程序执行过程中发生了不正常的情况，而这种不正常的情况叫做：异常<br>     java语言是很完善的语言，提供了异常的处理方式，以下程序执行过程中出现了不正常情况，<br>     java把该异常信息打印输出到控制台，供程序员参考。程序员看到异常信息之后，可以对<br>     程序进行修改，让程序更加的健壮。</p> 
<p>    什么是异常：程序执行过程中的不正常情况。<br>     异常的作用：增强程序的健壮性。</p> 
<p>2、以下程序执行控制台出现了：<br>     Exception in thread "main" java.lang.ArithmeticException: / by zero<br>         at com.bjpowernode.javase.exception.ExceptionTest01.main(ExceptionTest01.java:14)<br>     这个信息被我们称为：异常信息。这个信息是JVM打印的。</p> 
<p>3. 异常在java中以类的形式存在，每一个异常类都可以创建异常对象。</p> 
<p>4.处理异常的第一种方式：<br>     在方法声明的位置上使用throws关键字抛出，谁调用我这个方法，我就抛给谁。抛给调用者来处理。<br>     这种处理异常的态度：上报。</p> 
<p>  处理异常的第二种方式：<br>     使用try..catch语句对异常进行捕捉。<br>     这个异常不会上报，自己把这个事儿处理了。<br>     异常抛到此处为止，不再上抛了。</p> 
<p>注意：<br>     只要异常没有捕捉，采用上报的方式，此方法的后续代码不会执行。<br>     另外需要注意，try语句块中的某一行出现异常，该行后面的代码不会执行。<br>     try..catch捕捉异常之后，后续代码可以执行。</p> 
<p>在以后的开发中，处理编译时异常，应该上报还是捕捉呢，怎么选？<br>     如果希望调用者来处理，选择throws上报。<br>     其它情况使用捕捉的方式。</p> 
<p>5.深入try..catch<br>     1、catch后面的小括号中的类型可以是具体的异常类型，也可以是该异常类型的父类型。<br>     2、catch可以写多个。建议catch的时候，精确的一个一个处理。这样有利于程序的调试。<br>     3、catch写多个的时候，从上到下，必须遵守从小到大。</p> 
<p>6.异常对象的两个方法：<br>     String msg = e.getMessage();<br>     e.printStackTrace(); // 一般都是使用这个。</p> 
<p>我们以后查看异常的追踪信息，我们应该怎么看，可以快速的调试程序呢？<br>     异常信息追踪信息，从上往下一行一行看。<br>     但是需要注意的是：SUN写的代码就不用看了(看包名就知道是自己的还是SUN的。)。<br>     主要的问题是出现在自己编写的代码上。</p> 
<p>例如：</p> 
<p>/*<br>             java.io.FileNotFoundException: C:\jetns-agent.jar (系统找不到指定的文件。)<br>                 at java.base/java.io.FileInputStream.open0(Native Method)<br>                 at java.base/java.io.FileInputStream.open(FileInputStream.java:213)<br>                 at java.base/java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:155)<br>                 at java.base/java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:110)                    //sun的代码<br>                 at com.bjpowernode.javase.exception.ExceptionTest09.m3(ExceptionTest09.java:31)  //自己代码出现的异常<br>                 at com.bjpowernode.javase.exception.ExceptionTest09.m2(ExceptionTest09.java:27)<br>                 at com.bjpowernode.javase.exception.ExceptionTest09.m1(ExceptionTest09.java:23)<br>                 at com.bjpowernode.javase.exception.ExceptionTest09.main(ExceptionTest09.java:14)<br>                 因为31行出问题导致了27行<br>                 27行出问题导致23行<br>                 23行出问题导致14行。<br>                 应该先查看31行的代码。31行是代码错误的根源。</p> 
<p>7.关于try..catch中的finally子句：<br>     1、在finally子句中的代码是最后执行的，并且是一定会执行的，即使try语句块中的代码出现了异常。<br>         finally子句必须和try一起出现，不能单独编写。</p> 
<p>    2、finally语句通常使用在哪些情况下呢？<br>         通常在finally语句块中完成资源的释放/关闭。<br>         因为finally中的代码比较有保障。<br>         即使try语句块中的代码出现异常，finally中代码也会正常执行。</p> 
<p>8.finally语句：<br>     放在finally语句块中的代码是一定会执行的【再次强调！！！】<br>  */<br> 例一：public class ExceptionTest11 {<!-- --><br>     public static void main(String[] args) {<!-- --><br>         /*<br>         try和finally，没有catch可以吗？可以。<br>             try不能单独使用。<br>             try finally可以联合使用。<br>         以下代码的执行顺序：<br>             先执行try...<br>             再执行finally...<br>             最后执行 return （return语句只要执行方法必然结束。）<br>          */<br>         try {<!-- --><br>             System.out.println("try...");<br>             return;<br>         } finally {<!-- --><br>             // finally中的语句会执行。能执行到。<br>             System.out.println("finally...");<br>         }</p> 
<p>        // 这里不能写语句，因为这个代码是无法执行到的。<br>         //System.out.println("Hello World!");<br>     }<br> }<br> 例二：public class ExceptionTest12 {<!-- --><br>     public static void main(String[] args) {<!-- --><br>         try {<!-- --><br>             System.out.println("try...");<br>             // 退出JVM<br>             System.exit(0); // 退出JVM之后，finally语句中的代码就不执行了！<br>         } finally {<!-- --><br>             System.out.println("finally...");<br>         }<br>     }<br> }</p> 
<p> </p> 
<p>9.反编译.class文件案例    反编译工具DJ  decompile</p> 
<p>public class ExceptionTest13 {<!-- --><br>     public static void main(String[] args) {<!-- --><br>         int result = m();<br>         System.out.println(result); //100<br>     }</p> 
<p>    /*<br>     java语法规则（有一些规则是不能破坏的，一旦这么说了，就必须这么做！）：<br>         java中有一条这样的规则：<br>             方法体中的代码必须遵循自上而下顺序依次逐行执行（亘古不变的语法！）<br>         java中还有一条语法规则：<br>             return语句一旦执行，整个方法必须结束（亘古不变的语法！）<br>      */<br>     public static int m(){<!-- --><br>         int i = 100;<br>         try {<!-- --><br>             // 这行代码出现在int i = 100;的下面，所以最终结果必须是返回100<br>             // return语句还必须保证是最后执行的。一旦执行，整个方法结束。<br>             return i;<br>         } finally {<!-- --><br>             i++;<br>         }<br>     }<br> }</p> 
<p>/*<br> 反编译之后的效果<br> public static int m(){<!-- --><br>     int i = 100;<br>     int j = i;<br>     i++;<br>     return j;<br> }<br>  */</p> 
<p>10.final finally finalize有什么区别？<br>     final 关键字<br>         final修饰的类无法继承<br>         final修饰的方法无法覆盖<br>         final修饰的变量不能重新赋值。</p> 
<p>    finally 关键字<br>         和try一起联合使用。<br>         finally语句块中的代码是必须执行的。</p> 
<p>    finalize 标识符<br>         是一个Object类中的方法名。<br>         这个方法是由垃圾回收器GC负责调用的。</p> 
<p>11.Java中怎么自定义异常呢？（重要***）<br>     两步：<br>         第一步：编写一个类继承Exception或者RuntimeException.<br>         第二步：提供两个构造方法，一个无参数的，一个带有String参数的。</p> 
<p>    死记硬背。<br>  */<br> public class MyException extends Exception{ // 编译时异常<br>     public MyException(){<!-- --></p> 
<p>    }<br>     public MyException(String s){<!-- --><br>         super(s);<br>     }<br> }</p> 
<p>/*<br> public class MyException extends RuntimeException{ // 运行时异常</p> 
<p>}<br>  */<br>  </p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/6942b5b15041524712d7536cef162c07/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">C语言文件操作详解</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/21412c163a22637d9dffc7e66491b365/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">Bugku解题 web (一)</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大白的博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>