<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>JDK动态代理UndeclaredThrowableException异常 - 编程大白的博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="JDK动态代理UndeclaredThrowableException异常" />
<meta property="og:description" content="UndeclaredThrowableException异常背景 最近项目上出现了 JDK动态代理UndeclaredThrowableException异常，此异常之前没有接触过，那么该异常将会导致什么呢？
UndeclaredThrowableException后果：导致该抛出的直接异常信息被包装了好几层，异常看起来很费事，如下图：
产生原因 要了解其原因的前提条件是必须了解检查型异常和非检查型异常，了解的话请查看这个链接：检查型异常和非检查型异常 为什么会产生UndeclaredThrowableException异常呢？通过查阅javadoc官方文档（链接地址：https://docs.oracle.com/javase/6/docs/api/java/lang/reflect/InvocationHandler.html），发现了该异常抛出的条件，如下图：
上述原因翻译成关键一句就是：如果抛出的异常是检查型异常，而代理类在处理异常时没有发现该类型的异常在接口中声明
这种话是什么意思呢？下面结合代码给大家讲述一下，动态代理之后会生成$Proxy0.class文件，至于怎么生成并查看这个文件，请查看这个链接：JDK动态代理文件$Proxy0.class的生成和查看， $Proxy0.class 文件内容说明了如何抛出了UndeclaredThrowableException异常，如下图：
通过JDK动态代理代码调用我们发现，method.invoke(target, args) 将会抛出 InvocationTargetException ，InvocationTargetException 异常属于检查型异常，如下图：
而代码中接口声明的是非检查型异常RuntimeException，因此会抛出 UndeclaredThrowableException异常，示例demo如下所示：
// 自定义异常 public class CustomException extends RuntimeException { private static final long serialVersionUID = -5427543428947291283L; public CustomException(String message) { super(message); } } // 接口 public interface AccountService { void getAccount() throws RuntimeException; } // 实现类 public class AccountServiceImpl implements AccountService { @Override public void getAccount() throws RuntimeException { try { System." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://bcdabai.github.io/posts/8554e15f67b5440c151b13b32f3a98c0/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2019-06-17T15:19:03+08:00" />
<meta property="article:modified_time" content="2019-06-17T15:19:03+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大白的博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大白的博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">JDK动态代理UndeclaredThrowableException异常</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <h4>UndeclaredThrowableException异常背景</h4> 
<p>最近项目上出现了 JDK动态代理UndeclaredThrowableException异常，此异常之前没有接触过，那么该异常将会导致什么呢？</p> 
<p>UndeclaredThrowableException后果：导致该抛出的直接异常信息被包装了好几层，异常看起来很费事，如下图：</p> 
<p><img alt="" class="has" height="245" src="https://images2.imgbox.com/22/7f/swBN6Srx_o.png" width="1199"></p> 
<h4>产生原因</h4> 
<p>要了解其原因的前提条件是必须了解检查型异常和非检查型异常，了解的话请查看这个链接：<a href="https://blog.csdn.net/u013630349/article/details/50850880">检查型异常和非检查型异常</a> </p> 
<p>为什么会产生UndeclaredThrowableException异常呢？通过查阅javadoc官方文档（链接地址：<a href="https://docs.oracle.com/javase/6/docs/api/java/lang/reflect/InvocationHandler.html" rel="nofollow">https://docs.oracle.com/javase/6/docs/api/java/lang/reflect/InvocationHandler.html</a>），发现了该异常抛出的条件，如下图：</p> 
<p><img alt="" class="has" height="524" src="https://images2.imgbox.com/cf/d9/8veH6GqC_o.png" width="1200"></p> 
<p>上述原因翻译成关键一句就是：<span style="color:#f33b45;"><strong>如果抛出的异常是检查型异常，而代理类在处理异常时没有发现该类型的异常在接口中声明</strong></span></p> 
<p>这种话是什么意思呢？下面结合代码给大家讲述一下，动态代理之后会生成<strong><span style="color:#f33b45;">$Proxy0.class</span></strong>文件，至于怎么生成并查看这个文件，请查看这个链接：<a href="https://blog.csdn.net/ywlmsm1224811/article/details/92583559">JDK动态代理文件$Proxy0.class的生成和查看</a>， $Proxy0.class 文件内容说明了如何抛出了UndeclaredThrowableException异常，如下图：</p> 
<p><img alt="" class="has" height="903" src="https://images2.imgbox.com/9f/5e/AFjZcvFG_o.png" width="884"></p> 
<p>通过JDK动态代理代码调用我们发现，<strong>method.invoke(target, args) 将会抛出 InvocationTargetException ，InvocationTargetException 异常属于检查型异常</strong>，如下图：</p> 
<p><img alt="" class="has" height="472" src="https://images2.imgbox.com/9d/ec/yENgD8Sa_o.png" width="795"></p> 
<p>而<strong>代码中接口声明的是非检查型异常RuntimeException，因此会抛出 UndeclaredThrowableException异常</strong>，示例demo如下所示：</p> 
<pre class="has"><code class="language-java">// 自定义异常

public class CustomException extends RuntimeException {
    private static final long serialVersionUID = -5427543428947291283L;

    public CustomException(String message) {
        super(message);
    }
}

// 接口

public interface AccountService {
    void getAccount() throws RuntimeException;
}

// 实现类

public class AccountServiceImpl implements AccountService {
    @Override
    public void getAccount() throws RuntimeException {
        try {
            System.out.println(1/0);
        } catch (Exception e) {
            throw new CustomException("账户查询异常：" + e);
        }
    }
}

// JDK动态代理类

public class AccountProxy implements InvocationHandler {
    private Object target;

    public AccountProxy(Object target) {
        this.target = target;
    }

    @Override
    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
        return method.invoke(target, args);
    }
}

// 测试类

public class ProxyTest {
    public static void main(String[] args) {
        System.getProperties().put("sun.misc.ProxyGenerator.saveGeneratedFiles","true");
        AccountService accountService = new AccountServiceImpl();
        AccountService accountServiceProxy = (AccountService) Proxy.newProxyInstance(accountService.getClass().getClassLoader(),
                accountService.getClass().getInterfaces(), new AccountProxy(accountService));

        try {
            accountServiceProxy.getAccount();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}</code></pre> 
<h4>避免抛出 UndeclaredThrowableException异常</h4> 
<p>那么针对上述代码，我们怎么样避免UndeclaredThrowableException异常的抛出呢？我们既然知道了该异常的抛出原因，那么只需要简单修改一下就可以避免此异常的抛出，即只需要将接口中抛出的异常修改为检查型异常即可，如下所示：</p> 
<pre class="has"><code class="language-java">// 接口中的 RuntimeException 修改为了 Exception

public interface AccountService {
    void getAccount() throws Exception;
}</code></pre> 
<p>代理类 $Proxy0.class 如下图所示：</p> 
<p><img alt="" class="has" height="906" src="https://images2.imgbox.com/64/c0/PYJXVb9g_o.png" width="903"></p> 
<p>注意： 这里的异常类型和你自定义异常的类型无关吗，只和代理类接口中声明的异常类型有关</p> 
<h3>完美的解决方案</h3> 
<p>我们不管代理接口中声明的抛出类型是什么，我们只想看到自己抛出的直接的异常，UndeclaredThrowableException异常 和 InvocationTargetException 异常都不想看到，这样更容易定位到问题。解决方案就是在 method.invoke(target, args) 进行 InvocationTargetException 异常的捕获，代码如下：</p> 
<pre class="has"><code class="language-java">// method.invoke(target, args) 方法调用地方增加了 InvocationTargetException 异常的捕获

public class AccountProxy implements InvocationHandler {
    private Object target;

    public AccountProxy(Object target) {
        this.target = target;
    }

    @Override
    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
        try {
            return method.invoke(target, args);
        } catch (InvocationTargetException e) {
            throw e.getCause();
        }
    }
}</code></pre> 
<p>运行结果如下图所示：</p> 
<p><img alt="" class="has" height="499" src="https://images2.imgbox.com/3b/b4/UyNUgPqu_o.png" width="1200"></p> 
<h4>总结</h4> 
<p>通过上述分析可知，<span style="color:#f33b45;"><strong>当我们使用JDK动态代理的时候，需要捕获 method.invoke(target, args) 抛出的 InvocationTargetException 异常</strong></span></p> 
<p><strong>代理类中为什么对未声明的检查型异常转换为 UndeclaredThrowableException 异常呢？答案是 <span style="color:#f33b45;">java 继承原则，即子类覆盖父类方法或者实现父类方法时，抛出的异常必须在父类支持的异常列表之内。</span></strong></p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/17a796420fa1046a02f66a47e8697245/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">生成假的规则单号？</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/84f443fabddb15bb17efc143c872f0f0/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">常见虚拟机对比</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大白的博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>