<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>golang 详解协程——errgroup - 编程大白的博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="golang 详解协程——errgroup" />
<meta property="og:description" content="为什么要有sync.errgroup
go支持并发，一般采用的是 channel 、 sync.WaitGroup 、context，来实现各个协程之间的流程控制和消息传递。
但是对于开启的成千上万的协程，如果在每个协程内都自行去打印 错误日志的话，会造成日志分散，不好分析。
所以我们要实现一种能统一处理各个协程错误的工具
什么是 sync.errgroup
Go团队在实验仓库中添加了一个名为sync.errgroup的新软件包。 sync.ErrGroup再sync.WaitGroup功能的基础上，增加了错误传递，以及在发生不可恢复的错误时取消整个goroutine集合，或者等待超时
主要是利用了 waitgroup,context以及sync.Once，对这三个不熟悉的应先去看下相应的知识点获取方法
go get golang.org/x/sync
1
errgroup 的功能
1、处理子协程 error
func main() { var g errgroup.Group // 声明一个group实例 var urls = []string{ &#34;http://www.golang.org/&#34;, &#34;http://www.google.com/&#34;, &#34;http://www.somestupidname.com/&#34;, } for _, url := range urls { // 分别获取网站内容 url := url // url是局部变量，for循环中对多个协程传递值时，需要重新进行赋值 g.Go(func() error { // group 的go方法，启一个协程去执行代码 // Fetch the URL. resp, err := http.Get(url) if err == nil { resp." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://bcdabai.github.io/posts/5e4db31325387e42751c994df6692f18/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2023-11-04T19:07:24+08:00" />
<meta property="article:modified_time" content="2023-11-04T19:07:24+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大白的博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大白的博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">golang 详解协程——errgroup</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p>为什么要有sync.errgroup<br> go支持并发，一般采用的是 channel 、 sync.WaitGroup 、context，来实现各个协程之间的流程控制和消息传递。<br> 但是对于开启的成千上万的协程，如果在每个协程内都自行去打印 错误日志的话，会造成日志分散，不好分析。<br> 所以我们要实现一种能统一处理各个协程错误的工具</p> 
<p>什么是 sync.errgroup<br> Go团队在实验仓库中添加了一个名为sync.errgroup的新软件包。 sync.ErrGroup再sync.WaitGroup功能的基础上，增加了错误传递，以及在发生不可恢复的错误时取消整个goroutine集合，或者等待超时</p> 
<p>主要是利用了 waitgroup,context以及sync.Once，对这三个不熟悉的应先去看下相应的知识点获取方法<br> go get golang.org/x/sync<br> 1<br> errgroup 的功能<br> 1、处理子协程 error</p> 
<pre><code class="hljs">func main() {
	var g errgroup.Group  // 声明一个group实例
	var urls = []string{
		"http://www.golang.org/",
		"http://www.google.com/",
		"http://www.somestupidname.com/",
	}
	for _, url := range urls {  // 分别获取网站内容
		url := url // url是局部变量，for循环中对多个协程传递值时，需要重新进行赋值
		g.Go(func() error {  // group 的go方法，启一个协程去执行代码
			// Fetch the URL.
			resp, err := http.Get(url)
			if err == nil {
				resp.Body.Close()
			}
			return err
		})
	}
	if err := g.Wait(); err == nil {  // group 的wait方法，等待上面的 g.go的协程执行完成，并且可以接受错误
		fmt.Println("Successfully fetched all URLs.")
	}
}</code></pre> 
<p>上面这个例子是简单的利用 errgroup 进行的 waitGroup和error的处理，下面我们对关键的代码做一个分析，并结合源码来看</p> 
<p>var g errgroup.Group<br> 声明一个 group的实例，我们看下 group 包含哪些东西</p> 
<pre><code class="hljs">type Group struct {
	cancel func()

	wg sync.WaitGroup

	errOnce sync.Once
	err     error
}
</code></pre> 
<p>group是一个结构体，包含四个部分</p> 
<p>cancel 一个取消的函数，主要来包装context.WithCancel的CancelFunc<br> wg 借助于WaitGroup实现的<br> errOnce 使用sync.Once实现只输出第一个err<br> err 记录下错误的信息<br> g.Go(func() error {}<br> 启动goroutine 执行代码<br> 记录第一个出错的goroutine的err信息。我们看下源码</p> 
<pre><code class="hljs">func (g *Group) Go(f func() error) {
	g.wg.Add(1)  // 和WaitGroup 一样，每执行一个新的g，通过add方法 加1

	go func() {
		defer g.wg.Done() // 执行结束后 调用 Done方法，减1

		if err := f(); err != nil {  // 执行传入的匿名函数
			g.errOnce.Do(func() {   // 如果匿名函数返回错误，会记录错误信息。注意这里用的 once.Do，只执行一次，仅会记录第一个出现的err
				g.err = err
				if g.cancel != nil {  // 如果初始化的有 cancel 函数，会调用 cancel退出
					g.cancel()
				}
			})
		}
	}()
}
</code></pre> 
<p>再来看下 g.Wait()func (g *Group) Wait() error {<!-- --></p> 
<pre><code class="hljs">func (g *Group) Wait() error {
	g.wg.Wait()  // 和 WaitGroup 一样，在主线程调用 wait 方法，阻塞等待所有g执行完成
	if g.cancel != nil {  // 如果初始化了 cancel 函数，就执行
		g.cancel()
	}
	return g.err  // 返回第一个出现的err信息
}
</code></pre> 
<p>2、结合 context 来使用</p> 
<pre><code class="hljs">package main

import (
	"context"
	"fmt"
	"golang.org/x/sync/errgroup"
	"time"
)

func main() {
	ctx, cancel := context.WithCancel(context.Background())
	group, errCtx := errgroup.WithContext(ctx)

	for index := 0; index &lt; 3; index++ {
		indexTemp := index

		// 新建子协程
		group.Go(func() error {
			fmt.Printf("indexTemp=%d \n", indexTemp)
			if indexTemp == 0 { // 第一个协程
				fmt.Println("indexTemp == 0 start ")
				fmt.Println("indexTemp == 0 end")
			} else if indexTemp == 1 { // 第二个协程
				fmt.Println("indexTemp == 1 start")
				//这里一般都是某个协程发生异常之后，调用cancel()
				//这样别的协程就可以通过errCtx获取到err信息，以便决定是否需要取消后续操作
				cancel() // 第二个协程异常退出
				fmt.Println("indexTemp == 1 err ")
			} else if indexTemp == 2 {
				fmt.Println("indexTemp == 2 begin")

				// 休眠1秒，用于捕获子协程2的出错
				time.Sleep(1 * time.Second)

				//检查 其他协程已经发生错误，如果已经发生异常，则不再执行下面的代码
				err := CheckGoroutineErr(errCtx) // 第三个协程感知第二个协程是否正常
				if err != nil {
					return err
				}
				fmt.Println("indexTemp == 2 end ")
			}
			return nil
		})
	}

	// 捕获err
	err := group.Wait()
	if err == nil {
		fmt.Println("都完成了")
	} else {
		fmt.Printf("get error:%v", err)
	}
}

//校验是否有协程已发生错误
func CheckGoroutineErr(errContext context.Context) error {
	select {
	case &lt;-errContext.Done():
		return errContext.Err()
	default:
		return nil
	}
}</code></pre> 
<p><br> 可以结合contex 来实现主动退出及超时控制<br> ————————————————<br> 版权声明：本文为CSDN博主「老赵骑摩托」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。<br> 原文链接：https://blog.csdn.net/weixin_43753680/article/details/118514525</p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/a420899739b8d50a6e829f0e33dddfb6/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">全网免费Token的生成和解析,第一期</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/971cf1da8d89e896afc7ed0424cd8232/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">NewStars Moe CTF2023</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大白的博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>